version: "3.9"
services:
  web:
    depends_on:
      - db
    build: .
    volumes:
      - .:/home/app
    ports:
      - 3000:3000
    command: >
      sh -c "
        cd /home/app;
        bundle install; # Make sure Gemfile.lock got updated to be commited
        yarn install; # Make sure yarn.lock got updated to be commited
        rails db:prepare;
        rm ./tmp/pids/server.pid;
        rails s -b '0.0.0.0';
      "
    environment:
      # To edit credentials.yml.enc
      - EDITOR=vi
    # To use pry, with `docker attach $(docker-compose ps -q web)`
    stdin_open: true
    # To have more colorful output on pry
    tty: true
  db:
    image: postgres:12.5-alpine
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  db_volume:

